# This is a file with almost complete explanation of numpy with examples 

## > Before code: NumPy is about N-dimensional arrays

## > Everything in NN math is: vectors,matrices,tensors

## > NumPy does fast vectorized(doing math on whole arrays at once in compiled C code instead of looping element by element in python) math

## > You never loop over samples or neurons unless debugging

## > If you loop → you’re thinking wrong.


# ndarray: The Only Object That Matters

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2],[3,4],[5,6]]])

In [4]:
print(a,b)

[1 2 3] [[1 2]
 [3 4]]


In [5]:
print(type(a),type(b))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


# 2. Shape, ndim, size

In [6]:
# shape of arrya object a 
a.shape

(3,)

In [7]:
b.shape


(2, 2)

In [8]:
# outer brackte [[....]]-> counts 1 single entire list inside
# inside 2nd list [[] [] []] -> counts these as 3 lists as they are
# and 3rd list [] -> which has 2 values s
c.shape

(1, 3, 2)

In [9]:
# dimension of a object
a.ndim

1

In [10]:
b.ndim

2

In [11]:
a.size # x.size == np.prod(np.shape)
b.size
c.size # so size of c == (1*2*3) which was it's size

6

# ndim  → how many axes
# shape → length of each axis
# size  → total elements

# 3. Data Types

In [12]:
a.dtype
b.dtype
c.dtype

dtype('int64')

In [13]:
# can also be used for 

x = np.array([1,2,3], dtype=np.float64)
x.dtype
x

array([1., 2., 3.])

# 4. Different ways to create Array

In [14]:
np.zeros((3,4))
# creates an nd array with only 0 as elements, takes input tuple with shape values of the array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,2))
# works the same way as np.zeors and takes input of tuple of size

array([[1., 1.],
       [1., 1.]])

In [16]:
np.full((2,3),1)

# it's also a way of create an ndarray whose input can be read as 
# np.full((shape of array),value to be inserted in array)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.eye(4)
# creates an identity matrix of input * input(4*4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Creating using random numbers

In [18]:
np.random.rand(3,4)

# it creates a 2d array of shape (3,4)
# values are random floats
# drawn from a uniform distribution(each value is eaqually likely to come up)
# ranges for [0,1)

array([[0.04610252, 0.70145894, 0.41377603, 0.38681195],
       [0.0524515 , 0.43318298, 0.38154698, 0.69870032],
       [0.0151419 , 0.05215281, 0.63757363, 0.50364725]])

In [19]:
np.random.randn(3,4)
# follows standard normal distribution ( a bell shaped curve center at 0)
# mean 0 ( all the values averages out to 0)
# standard deviation 1 ( mean how spread out values from mean so between -1 and 1)
# other than that everything is same as random.rand and values are also not between 0 and 1

array([[-1.18250035, -1.82204464,  1.87566198, -0.23984283],
       [-0.06223306,  0.19692282, -0.6418884 , -0.16426389],
       [ 0.90344617, -0.49769679, -0.12809885, -0.52285168]])

In [20]:
np.random.randint(8,10,(3,4))
# Creates a 2D array of shape (3, 4)
# here shape is passed as a  tuple not spearate arguments in rand and randn
# Values are random integers

# Range: [x, y) → xtoy ( here x=8, y=10)

array([[8, 8, 9, 9],
       [8, 9, 9, 8],
       [8, 8, 8, 9]])

In [21]:
# start from randomness sequence associated with 42
np.random.seed(42)
np.random.rand()


0.3745401188473625

# 5. Indexing & Slicing

In [22]:
x = np.array([10,20,30,40])
x[0]
x[-1]
x[1:3]
x[-1:-3:-1]
# general slicing rule 
# [start:stop:step]
# step>0 left-> right
# step<0 right -> left

array([40, 30])

In [23]:
x[::] # entire array

array([10, 20, 30, 40])

In [24]:
x[::-1] # reverse array

array([40, 30, 20, 10])

### 2d and 3d

In [25]:
y = np.array([[1,2],[3,4],[4,5]])
print(y.shape)
print(y.ndim)

(3, 2)
2


In [26]:
y[0,1]
y[0]
y[0:2, :]

# here the rule stays the same start : stop : step 
# the only thing to remember is [rowsstart:rowsstop:rowstep, columnsstart:columnsstop:columnstep]

array([[1, 2],
       [3, 4]])

## important rule 
### slicing creates views, not copies

In [27]:
y

array([[1, 2],
       [3, 4],
       [4, 5]])

In [28]:
B = y[:,1]

In [29]:
B[0]=999

In [30]:
y

array([[  1, 999],
       [  3,   4],
       [  4,   5]])

In [31]:
# so value at y[0,1] also changed
# To copy:
C = y[:,1].copy()
C[2]=999

In [32]:
y

array([[  1, 999],
       [  3,   4],
       [  4,   5]])

# 6. Reshape, Flatten, Transpose

In [33]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
# reshape
# reshape() changes how the data is arranged into dimensions,
# without changing the data itself.
x.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
# if you use -1 in any axes numpy calculates values for that 
# the only rule is  product of new shape == total number of elements
x.reshape((3,-1))
x.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## flaten vs ravel

#### they both convert an array into a 1d array
### Method	    Returns	              Memory
### flatten()	copy	            new memory
### ravel()	    view (if possible)	no new memory

# 7. Transpose

In [36]:
y
#  transpose just means changing axis order  .transpose(new_axis_order)
# with a new axis order it simpley works like array.transpose(0,1,...ndim-1) == array.transpose(ndim-1, ..., 1, 0)


array([[  1, 999],
       [  3,   4],
       [  4,   5]])

In [37]:
y.transpose()

array([[  1,   3,   4],
       [999,   4,   5]])

In [38]:
y.T

array([[  1,   3,   4],
       [999,   4,   5]])

In [39]:
m = np.arange(24).reshape(2,3,4)
m.shape
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
t = m.transpose(2,0,1)
t.shape
t

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

# 8. Broadcasting

In [41]:
# The term broadcasting describes how NumPy  treats arrays 
# with  different shapes during arithmetic operations

In [42]:
# Broadcasting is NumPy pretending a smaller array is bigger, without actually copying data.

In [43]:
# NumPy compares shapes from RIGHT to LEFT.
# Two dimensions are compatible if:

# They are equal

# OR one of them is 1

In [44]:
a = np.array([256,256,3])
b = np.array([3])
a+b
# so here we compared shapes from right to left so (1,3),(1,1), as it satisfies one of them is 1 we can broadcast here

array([259, 259,   6])

In [45]:
A = np.array([3]) 
B = np.array([4])
A+B

array([7])

# 9. Elementwise operations

In [46]:
a+b
a-b
a*b
a/b
a**2
# these do not mean matrix math
# all element by element operation 

array([65536, 65536,     9])

# 10. Matrix multiplication

In [47]:
# for using these this rule is important: 
# (m, n) @ (n, p) → (m, p)
a = np.array((3,2))
b = np.array((2,3))
a @ b
np.dot(a,b)
np.matmul(a,b)
# this is the function behind @ exact same behaviour 

np.int64(12)

In [48]:
# Matrix multiplication cares about the last two axes.
# Broadcasting happens on all earlier axes.

# 11. Reductions(sum,mean,max,min,std)
    There are 2 rules for this:
       > Reduce Everything no axis
       > Reduce along an axis 

# common reduction functions
np.sum()
np.mean()
np.std()
np.median()
np.min()
np.max()


In [49]:
# 1 reduce everything 

a = np.array([[1,2,3],[4,5,6]])
np.sum(a)
# All elements are combined
# Output is a scalar
# Shape disappears
# works same for all others

np.int64(21)

In [50]:
# 2. Reduce along an axis
# General rule:
# axis = k means “collapse axis k”
# The result:
# removes that axis
# keeps the others

In [51]:
a = np.array([[1,2,3],[4,5,6]])

In [52]:
np.sum(a, axis=0)

array([5, 7, 9])

In [53]:
np.sum(a, axis=1)

array([ 6, 15])

### general rule of reductions for any dimensions 

In [56]:
# A reduction collapses an axis by looping over it, combining its values, and removing that axis from the array’s shape.

### Keepdims = True

In [57]:
# Instead of removing the reduced axis, NumPy keeps it and sets its size to 1.

# 12.Boolean Masks 

In [58]:
# Boolean Masks are like using if else conditions as indexing

In [61]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [62]:
mask = x>3
mask

array([False, False, False,  True,  True,  True])

In [63]:
# Boolean indexing selects elements where the mask is True.
x[mask]

array([4, 5, 6])

In [65]:
# Assigning values with boolean masks
x = np.array([1, 2, 3, 4, 5])
x[x > 3] = 0
x

array([1, 2, 3, 0, 0])

In [ ]:
#Boolean masks are vectorized if conditions used to select or modify array elements based on a condition

# 13. Universal Functions

In [68]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692,  1.        ,  1.        ])

In [69]:
np.log(x)

/tmp/ipykernel_5356/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([0.        , 0.69314718, 1.09861229,       -inf,       -inf])

In [70]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 0.        , 0.        ])

In [71]:
np.abs(x)

array([1, 2, 3, 0, 0])

In [72]:
np.maximum(x,0)
#compares a and b element-by-element and returns the larger value at each position.

array([1, 2, 3, 0, 0])

# 14. Numerical Stability

### rewriting mathematically equivalent expressions to keep intermediate values within safe numerical ranges.

In [73]:
np.exp(1000)# overflow

/tmp/ipykernel_5356/2006519253.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(1000)


np.float64(inf)

In [76]:
x[3] = 1000
x = x-np.max(x)
np.exp(x)

array([0., 0., 0., 1., 0.])

# 15. Stacking & Concatenation

In [91]:
A = np.arange(1,6)
B = np.arange(7,12)

In [92]:
np.concatenate([A,B], axis=0)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [93]:
np.vstack([A,B])
# All dimensions except axis 0 must match

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [95]:
np.hstack([A,B])

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

## Follow this strict discipline:

### 1. Every tensor has a documented shape

### 2. Never mix up: (n,),(n,1),(1,n)

### 3. Use keepdims=True

### 4. Avoid silent broadcasting unless intentional

### 5. Never guess shapes compute them