# This is a file with almost complete explanation of numpy with examples 

## > Before code: NumPy is about N-dimensional arrays

## > Everything in NN math is: vectors,matrices,tensors

## > NumPy does fast vectorized(doing math on whole arrays at once in compiled C code instead of looping element by element in python) math

## > You never loop over samples or neurons unless debugging

## > If you loop → you’re thinking wrong.


# ndarray: The Only Object That Matters

In [4]:
import numpy as np

In [23]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2],[3,4],[5,6]]])

In [17]:
print(a,b)

[1 2 3] [[1 2]
 [3 4]]


In [18]:
print(type(a),type(b))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


# 2. Shape, ndim, size

In [19]:
# shape of arrya object a 
a.shape

(3,)

In [20]:
b.shape


(2, 2)

In [21]:
# outer brackte [[....]]-> counts 1 single entire list inside
# inside 2nd list [[] [] []] -> counts these as 3 lists as they are
# and 3rd list [] -> which has 2 values s
c.shape

(1, 3, 2)

In [13]:
# dimension of a object
a.ndim

1

In [14]:
b.ndim

2

In [26]:
a.size # x.size == np.prod(np.shape)
b.size
c.size # so size of c == (1*2*3) which was it's size

6

# ndim  → how many axes
# shape → length of each axis
# size  → total elements

# 3. Data Types

In [30]:
a.dtype
b.dtype
c.dtype

dtype('int64')

In [34]:
# can also be used for 

x = np.array([1,2,3], dtype=np.float64)
x.dtype
x

array([1., 2., 3.])

# 4. Different ways to create Array

In [35]:
np.zeros((3,4))
# creates an nd array with only 0 as elements, takes input tuple with shape values of the array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones((2,2))
# works the same way as np.zeors and takes input of tuple of size

array([[1., 1.],
       [1., 1.]])

In [46]:
np.full((2,3),1)

# it's also a way of create an ndarray whose input can be read as 
# np.full((shape of array),value to be inserted in array)

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
np.eye(4)
# creates an identity matrix of input * input(4*4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Creating using random numbers

In [49]:
np.random.rand(3,4)

# it creates a 2d array of shape (3,4)
# values are random floats
# drawn from a uniform distribution(each value is eaqually likely to come up)
# ranges for [0,1)

array([[0.90681794, 0.22482142, 0.83024667, 0.72423219],
       [0.66038998, 0.82320411, 0.78221148, 0.46804836],
       [0.37765924, 0.27689908, 0.43028838, 0.23905502]])

In [50]:
np.random.randn(3,4)
# follows standard normal distribution ( a bell shaped curve center at 0)
# mean 0 ( all the values averages out to 0)
# standard deviation 1 ( mean how spread out values from mean so between -1 and 1)
# other than that everything is same as random.rand and values are also not between 0 and 1

array([[-1.61793581, -0.76514908, -0.29093652,  0.76718492],
       [-0.18017355, -0.21194774, -0.77484328,  0.21077511],
       [ 1.36301831,  0.08627145, -0.05690323,  0.07488697]])

In [52]:
np.random.randint(8,10,(3,4))
# Creates a 2D array of shape (3, 4)
# here shape is passed as a  tuple not spearate arguments in rand and randn
# Values are random integers

# Range: [x, y) → xtoy ( here x=8, y=10)

array([[8, 8, 9, 9],
       [9, 8, 8, 9],
       [9, 9, 9, 8]])

In [57]:
# start from randomness sequence associated with 42
np.random.seed(42)
np.random.rand()


0.3745401188473625

# 5. Indexing & Slicing

In [66]:
x = np.array([10,20,30,40])
x[0]
x[-1]
x[1:3]
x[-1:-3:-1]
# general slicing rule 
# [start:stop:step]
# step>0 left-> right
# step<0 right -> left

array([40, 30])

In [67]:
x[::] # entire array

array([10, 20, 30, 40])

In [68]:
x[::-1] # reverse array

array([40, 30, 20, 10])

### 2d and 3d

In [73]:
y = np.array([[1,2],[3,4],[4,5]])
print(y.shape)
print(y.ndim)

(3, 2)
2


In [76]:
y[0,1]
y[0]
y[0:2, :]

# here the rule stays the same start : stop : step 
# the only thing to remember is [rowsstart:rowsstop:rowstep, columnsstart:columnsstop:columnstep]

array([[1, 2],
       [3, 4]])

## important rule 
### slicing creates views, not copies

In [79]:
y

array([[1, 2],
       [3, 4],
       [4, 5]])

In [78]:
B = y[:,1]

In [80]:
B[0]=999

In [81]:
y

array([[  1, 999],
       [  3,   4],
       [  4,   5]])

In [86]:
# so value at y[0,1] also changed
# To copy:
C = y[:,1].copy()
C[2]=999

In [87]:
y

array([[  1, 999],
       [  3,   4],
       [  4,   5]])

# 6. Reshape, Flatten, Transpose

In [92]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
# reshape
# reshape() changes how the data is arranged into dimensions,
# without changing the data itself.
x.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
# if you use -1 in any axes numpy calculates values for that 
# the only rule is  product of new shape == total number of elements
x.reshape((3,-1))
x.reshape((-1,3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## flaten vs ravel

#### they both convert an array into a 1d array
### Method	Returns	Memory
### flatten()	copy	new memory
### ravel()	view (if possible)	no new memory

# Transpose